-- Insert authors with biographical information
INSERT INTO authors (name, nationality, birth_year, biography) VALUES
    ('Jane Austen', 'British', 1775, 'English novelist known for her romantic fiction and social commentary'),
    ('Herman Melville', 'American', 1819, 'American novelist and poet of the American Renaissance period'),
    ('Nathaniel Hawthorne', 'American', 1804, 'American novelist and short story writer'),
    ('Charlotte Bronte', 'British', 1816, 'English novelist and poet, famous for Jane Eyre'),
    ('Emily Bronte', 'British', 1818, 'English novelist and poet best known for Wuthering Heights'),
    ('Frank Herbert', 'American', 1920, 'Science fiction author best known for the Dune saga'),
    ('William Gibson', 'American', 1948, 'American-Canadian speculative fiction writer'),
    ('Neal Stephenson', 'American', 1959, 'American writer known for speculative fiction works'),
    ('Dan Simmons', 'American', 1948, 'American science fiction and horror writer'),
    ('Orson Scott Card', 'American', 1951, 'American novelist known for science fiction'),
    ('J.R.R. Tolkien', 'British', 1892, 'English writer, poet, and philologist'),
    ('Patrick Rothfuss', 'American', 1973, 'American fantasy writer'),
    ('Brandon Sanderson', 'American', 1975, 'American fantasy and science fiction writer'),
    ('Neil Gaiman', 'British', 1960, 'English author of short fiction and novels'),
    ('Christopher Paolini', 'American', 1983, 'American author of young adult fiction'),
    ('Yuval Noah Harari', 'Israeli', 1976, 'Israeli public intellectual and historian'),
    ('Tara Westover', 'American', 1986, 'American memoirist and historian'),
    ('Michelle Obama', 'American', 1964, 'American attorney and author, former First Lady'),
    ('Sun Tzu', 'Chinese', NULL, 'Ancient Chinese military strategist'),
    ('Matthew Walker', 'British', 1973, 'British scientist and professor of neuroscience'),
    ('Nicholas Sparks', 'American', 1965, 'American romance novelist'),
    ('Jojo Moyes', 'British', 1969, 'English journalist and romance novelist'),
    ('Sally Thorne', 'Australian', NULL, 'Australian romance author'),
    ('Stephenie Meyer', 'American', 1973, 'American young adult fiction author'),
    ('Diana Gabaldon', 'American', 1952, 'American author of historical romance'),
    ('Gillian Flynn', 'American', 1971, 'American author of mystery and thriller novels'),
    ('Stieg Larsson', 'Swedish', 1954, 'Swedish journalist and writer'),
    ('Liane Moriarty', 'Australian', 1966, 'Australian author'),
    ('Alex Michaelides', 'Cypriot-British', 1977, 'Author of psychological thrillers'),
    ('Dan Brown', 'American', 1964, 'American mystery-thriller novelist'),
    ('Stephen King', 'American', 1947, 'American author of horror and supernatural fiction'),
    ('Bram Stoker', 'Irish', 1847, 'Irish author best known for Gothic horror Dracula'),
    ('Josh Malerman', 'American', 1975, 'American author and singer'),
    ('Shirley Jackson', 'American', 1916, 'American writer known for horror and mystery'),
    ('Kristin Hannah', 'American', 1960, 'American author of historical fiction'),
    ('Anthony Doerr', 'American', 1973, 'American author of novels and short stories'),
    ('Markus Zusak', 'Australian', 1975, 'Australian writer of young adult fiction'),
    ('Kate Quinn', 'American', 1981, 'American historical fiction author'),
    ('Amor Towles', 'American', 1964, 'American novelist'),
    ('John Green', 'American', 1977, 'American author of young adult fiction'),
    ('Jenny Han', 'American', 1980, 'American author of young adult fiction'),
    ('Suzanne Collins', 'American', 1962, 'American author of young adult fiction'),
    ('Veronica Roth', 'American', 1988, 'American novelist and short story writer'),
    ('Victoria Aveyard', 'American', 1990, 'American writer of young adult fiction'),
    ('Sally Rooney', 'Irish', 1991, 'Irish author and screenwriter'),
    ('Cormac McCarthy', 'American', 1933, 'American novelist and playwright'),
    ('Fredrik Backman', 'Swedish', 1981, 'Swedish columnist and author'),
    ('Matt Haig', 'British', 1975, 'British author and journalist'),
    ('Tayari Jones', 'American', 1970, 'American novelist'),
    ('Donna Tartt', 'American', 1963, 'American author'),
    ('Delia Owens', 'American', 1949, 'American author and zoologist'),
    ('Hanya Yanagihara', 'American', 1974, 'American novelist and travel writer'),
    ('Khaled Hosseini', 'Afghan-American', 1965, 'Afghan-American novelist'),
    ('Toni Morrison', 'American', 1931, 'American novelist and professor'),
    ('James Clear', 'American', 1986, 'American author and entrepreneur'),
    ('Mark Manson', 'American', 1984, 'American self-help author'),
    ('Napoleon Hill', 'American', 1883, 'American self-help author'),
    ('Dale Carnegie', 'American', 1888, 'American writer and lecturer'),
    ('Don Miguel Ruiz', 'Mexican', 1952, 'Mexican author and spiritualist'),
    ('Walter Isaacson', 'American', 1952, 'American author and journalist'),
    ('Jeannette Walls', 'American', 1960, 'American author and journalist'),
    ('Tina Fey', 'American', 1970, 'American comedian and writer'),
    ('Art Spiegelman', 'American', 1948, 'American cartoonist and editor'),
    ('Alan Moore', 'British', 1953, 'English writer of comic books'),
    ('Marjane Satrapi', 'Iranian', 1969, 'Iranian-French graphic novelist'),
    ('Brian K. Vaughan', 'American', 1976, 'American comic book writer'),
    ('Rupi Kaur', 'Indian-Canadian', 1992, 'Indian-born Canadian poet'),
    ('T.S. Eliot', 'American-British', 1888, 'American-British poet and literary critic'),
    ('Walt Whitman', 'American', 1819, 'American poet and journalist'),
    ('Rumi', 'Persian', 1207, 'Persian poet and Sufi mystic'); 